# -*- coding: utf-8 -*-
"""AudioSample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/151X1RIAvO0QHcUG8-KzLgW14Dm_dYX7K
"""

import librosa
import soundfile as sf
import numpy as np

from google.colab import drive
drive.mount('/content/drive')
speech_file = "/content/drive/MyDrive/Speech enhancement/mlf_01130_00015565294.wav"       # Malayalam speech
noise_file  = "/content/drive/MyDrive/Speech enhancement/railway-station-3-56829.mp3" # Railway station ambience
output_file = "/content/mixed_sp01.wav"

target_sr = 16000   # resample both to 16kHz
snr_db = 5

speech, _ = librosa.load(speech_file, sr=target_sr)
noise, _  = librosa.load(noise_file, sr=target_sr)

if len(noise) < len(speech):
    # loop noise if too short
    repeats = int(np.ceil(len(speech) / len(noise)))
    noise = np.tile(noise, repeats)
noise = noise[:len(speech)]  # crop noise to speech length

speech_power = np.mean(speech**2)
noise_power = np.mean(noise**2)

# Compute scaling factor for noise
target_noise_power = speech_power / (10**(snr_db/10))
scaling_factor = np.sqrt(target_noise_power / (noise_power + 1e-8))
noise = noise * scaling_factor

mixed = speech + noise

sf.write(output_file, mixed, target_sr)
print(f"✅ Mixed file saved at: {output_file}")